spring:
  application:
    name: server-gateway
  profiles:
    active: dev # 通过环境变量或命令行启动指定：--spring.profiles.active=prod
  main:
    allow-bean-definition-overriding: true

custom:
  nacos:
    dev-namespace: 1555926c-7e69-4779-868f-5b57b13cda4e
    prod-namespace: a123456b-7890-4444-cccc-df890123abcd
